booking/urls.py
from django.urls import path
from .views import(
    AddBooking, 
    BookingList, 
    EditBooking, 
    DeleteBooking,
    BookingSuccess
)

app_name = 'booking'

urlpatterns = [
    path('', AddBooking.as_view(), name='add_booking'),
    path('success/<int:pk>', BookingSuccess.as_view(), name='booking_success'),
    path('list/', BookingList.as_view(), name='booking_list'),
    path('edit/<int:pk>', EditBooking.as_view(), name='edit_booking'),
    path('delete/<int:pk>/', DeleteBooking.as_view(), name='delete_booking'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('about/', views.about_page, name='about'),
]

la_hotel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('profiles/', include('guests.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
    path('rooms/', include('rooms.urls'), name='rooms'),
    path('booking/', include('booking.urls'), name='booking'),
]

rooms/urls.py
from django.urls import path
from .views import RoomCategoryList, RoomCategoryDetail

app_name = 'rooms'

urlpatterns = [
    path('', RoomCategoryList.as_view(), name='roomcategory'),
    path('<int:pk>/', RoomCategoryDetail.as_view(),
         name='roomcategory_detail'),
]

home/models.py
from django.db import models
from django_resized import ResizedImageField

# Create your models here.


class Hotel(models.Model):
    """
    Define the hotel information
    """
    name = models.CharField(
        max_length=100, unique=True, blank=False, null=False)
    adress = models.CharField(
        max_length=100, blank=False, null=False)
    zip_code = models.CharField(
        max_length=20, blank=False, null=False)
    city = models.CharField(
        max_length=100, blank=False, null=False)
    email = models.EmailField(
        max_length=100, unique=True, blank=False, null=False)
    phone = models.CharField(
        max_length=20, unique=True, blank=False, null=False)
    image = ResizedImageField(
        size=[550, None], quality=75, upload_to="hotel",
        force_format="WEBP", blank=False, null=False
    )
    image_alt = models.CharField(
        max_length=100, help_text="Enter a breif description of the image",
        default="placeholder default hotel image",
        blank=False, null=False
    )
    description = models.TextField(
        help_text="Enter a description of the hotel", blank=False, null=False)
    avaliable_rooms = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f'Hotel name: {self.name}'
        

home/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def home_page(request):
    return render(request, 'home/index.html')


def about_page(request):
    return render(request, 'home/about.html')

home/templates/home/about.html
{% extends 'base.html' %}
<!--Prettier Ignore-->
{% load static %}
<!--Prettier Ignore-->
{% block title %}About Us{% endblock %}


{% block content %}

<div class="container text-center">
    <h1 class="mt-5">About Us</h1>
    <p class="mb-4">Located in the picturesque coastal town of Landskrona, Sweden, Landskrona Hotel offers a quintessential blend of modern luxury and historic charm. Nestled along the stunning shoreline, our hotel provides guests with breathtaking views of the Baltic Sea and a tranquil retreat from the hustle and bustle of everyday life.</p>

    <h2>Luxurious Accommodations</h2>

    <p>Step into a world of elegance and comfort with our beautifully appointed rooms and suites. Each space is designed to reflect both contemporary style and local Scandinavian influences, ensuring a relaxing and rejuvenating stay for every guest.</p>

    <h2>Exceptional Dining</h2>

    <p>Indulge your palate at our on-site restaurant, where our talented chefs craft exquisite dishes using locally sourced ingredients. Whether you're enjoying a leisurely breakfast, a business lunch, or a romantic dinner overlooking the sea, our culinary offerings promise to delight even the most discerning food enthusiast.</p>

    <h2>Unparalleled Service</h2>

    <p>At Landskrona Hotel, our commitment to hospitality is unmatched. From the moment you arrive until your departure, our friendly and professional staff are dedicated to ensuring your every need is met with warmth and efficiency. Whether it's arranging local excursions, booking spa treatments, or providing personalized recommendations, we strive to create a seamless and memorable experience for our guests.</p>

    <h2>Explore Landskrona</h2>

    <p>Beyond the hotel, discover the charm of Landskrona itself. Wander through historic streets lined with colorful buildings, visit cultural landmarks, or simply relax on the sandy beaches nearby. With its rich history, vibrant arts scene, and stunning natural beauty, Landskrona offers something for everyone to enjoy.</p>

    <h2>Plan Your Stay</h2>

    <p>Whether you're visiting for business or pleasure, Landskrona Hotel is your ideal choice for accommodations in this enchanting coastal town. Experience luxury, comfort, and genuine hospitality at Landskrona Hotel—your home away from home in Sweden.</p>

    <h3 class="my-5">Welcome to us!</h3>
</div>

{%endblock%}

home/templates/home/carousel.html
{% load static %}

<div class="container my-5">
		<div id="carouselExampleRide" class="carousel slide custom-carousel-container" data-bs-ride="true">
			<div class="carousel-inner">
				<div class="carousel-item active">
					<img
						src="{% static 'images/standard-home.webp' %}"
						class="d-block w-100 custom-carousel-img"
						alt="Standard bedroom of the hotel"
					/>
					<div class="carousel-caption d-none d-md-block">
						<div class="transparent-box">
							<h3 class="text-green">Standard Room</h3>
							<p>With a double bed and garden view.</p>
						</div>
					</div>
				</div>
				<div class="carousel-item">
					<img
						src="{% static 'images/default-room-deluxe.webp' %}"
						class="d-block w-100 custom-carousel-img"
						alt="Deluxe bedroom of the hotel"
					/>
					<div class="carousel-caption d-none d-md-block">
						<div class="transparent-box">
							<h3 class="text-green">Deluxe Room</h3>
							<p>With a queen size bed and sea view.</p>
						</div>
					</div>
				</div>
				<div class="carousel-item">
					<img
						src="{% static 'images/default-suite-room.jpg' %}"
						class="d-block w-100 custom-carousel-img"
						alt="Suite bedroom of the hotel"
					/>
					<div class="carousel-caption d-none d-md-block">
						<div class="transparent-box">
							<h3 class="text-green">Suite</h3>
							<p>With a king size bed and sea view.</p>
						</div>
					</div>
				</div>
			</div>
			<button
				class="carousel-control-prev"
				type="button"
				data-bs-target="#carouselExampleRide"
				data-bs-slide="prev"
				aria-label="Previous"
			>
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="visually-hidden">Previous</span>
			</button>
			<button
				class="carousel-control-next"
				type="button"
				data-bs-target="#carouselExampleRide"
				data-bs-slide="next"
				aria-label="Next"
			>
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="visually-hidden">Next</span>
			</button>
		</div>
</div>

home/templates/home/index.html
{% extends 'base.html' %}
<!--Prettier Ignore-->
{% load static %}
<!--Prettier Ignore-->
{% block title %}Home{% endblock %}

<!-- Hero Section -->
{% block content %}
<section id="hero">
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-4">Landskrona Hotel</h1>
          <p class="lead">Welcome to our luxurious space right by the ocean!</p>
          <p>Book a room or Sign in to view your reservations</p>
          <a
            class="btn btn-md btn-book mx-4"
            href="{% url 'booking:add_booking' %}"
            role="button"
            aria-label="Book a room"
            >Book Now</a
          >
          {% if not user.is_authenticated %}
          <a class="btn btn-md mx-1"
            href="/accounts/login/"
            role="button"
            aria-label="Sign in to your account"
            >Sign In</a
          >
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Intro Section-->
<section id="intro">
  <div class="container d-flex flex-column mt-3">
    <div class="row">
      <div class="col-md-6 d-none d-md-block">
        <img
          src="{% static 'images/la-home1.webp' %}"
          alt="Landskrona waterfront from a drone view"
          class="img-fluid cover-img"
        >
      </div>
      <div class="col-md-6 mt-5 px-5">
        <h2 id="intro-heading" class="mb-4">Nestled along the stunning coastline...</h2>
        <p>
          Landskrona Hotel offers a luxurious retreat with breathtaking ocean
          views, elegant rooms, and top-notch amenities. <br />
          Whether for a relaxing getaway or a business trip, our dedicated staff
          ensures a memorable stay. <br /><br />
          Our hotel is located in the heart of Landskrona, a charming town with
          a rich history and vibrant culture.
        </p>
        <a
          class="btn btn-gold mt-4"
          href="{% url 'rooms:roomcategory' %}"
          role="button"
          aria-label="Find your stay"
          >Find Your Room
        </a>
      </div>
    </div>
  </div>
</section>
<!-- Room Carousel -->
<section id="room-carousel">
  <div class="container d-flex flex-column">
    <div class="col-12 text-center mt-5">
      <h2>Discover Our Rooms</h2>
    </div>
    {% include 'home/carousel.html' %}
  </div>
</section>
<!-- Manage Booking Details -->
<section id="manage-booking">
  <div class="container d-flex flex-row flex-wrap justify-content-center">
    <h2 class="text-center mt-4 d-block">Manage your bookings</h2>
    <div class="container">
      <div class="row mt-5">
        <div class="col-md-4 mb-4">
          <div class="card h-100 manage-card">
            <div class="card-body">
              <h3 class="card-title text-h3">1. Review Details</h3>
              <p class="card-text">View details of your reservation.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-4">
          <div class="card h-100 manage-card">
            <div class="card-body">
              <h3 class="card-title text-h3">2. Modify Reservations</h3>
              <p class="card-text">Make changes to your reservation.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-4">
          <div class="card h-100 manage-card">
            <div class="card-body">
              <h3 class="card-title text-h3">3. Cancel Reservations</h3>
              <p class="card-text">
                Cancel your existing booking up to 24h before check in.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="row my-4">
        <div class="col text-center">
          <a
            class="btn btn-gold mt-4"
            href="{% url 'booking:booking_list' %}"
            role="button"
            aria-label="View your reservations"
            >View Your Reservations
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Contact Us Section -->
<section id="contact-us">
  <div class="container mt-5">
    <h2 class="text-center mb-5">Contact Us</h2>
    <div class="row contact-container">
      <div class="col-12 col-md-6 mb-4">
        <div class="contact-info text-center">
          <div class="details">
            <p><i class="fas fa-envelope icon text-green-p" aria-hidden="true"></i>Email:</p>
            <p><a href="mailto:lahotel@example.com">landskrona.hotel@gmail.com</a></p>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-6 mb-4">
        <div class="contact-info text-center">
          <div class="details">
            <p><i class="fas fa-phone icon text-green-p" aria-hidden="true"></i>Phone:</p>
            <p>+46 34567890</p>
          </div>
        </div>
      </div>
      <div class="col-12 mb-4">
        <div class="contact-info text-center">
          <div class="details">
            <p>
              <i class="fas fa-map-marker-alt icon text-green-p" aria-hidden="true"></i>Address:
            </p>
            <p>123 Citadel Street, Landskrona, Sweden</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}