booking/urls.py
from django.urls import path
from .views import(
    AddBooking, 
    BookingList, 
    EditBooking, 
    DeleteBooking,
    BookingSuccess
)

app_name = 'booking'

urlpatterns = [
    path('', AddBooking.as_view(), name='add_booking'),
    path('success/<int:pk>', BookingSuccess.as_view(), name='booking_success'),
    path('list/', BookingList.as_view(), name='booking_list'),
    path('edit/<int:pk>', EditBooking.as_view(), name='edit_booking'),
    path('delete/<int:pk>/', DeleteBooking.as_view(), name='delete_booking'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('about/', views.about_page, name='about'),
]

la_hotel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('profiles/', include('guests.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
    path('rooms/', include('rooms.urls'), name='rooms'),
    path('booking/', include('booking.urls'), name='booking'),
]

rooms/urls.py
from django.urls import path
from .views import RoomCategoryList, RoomCategoryDetail

app_name = 'rooms'

urlpatterns = [
    path('', RoomCategoryList.as_view(), name='roomcategory'),
    path('<int:pk>/', RoomCategoryDetail.as_view(),
         name='roomcategory_detail'),
]

booking/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils import timezone

from djmoney.models.fields import MoneyField
from datetime import date

from django.contrib.auth.models import User
from rooms.models import Room, RoomCategory

# Create your models here.


class Booking(models.Model):
    """
    Represents a booking made by a user for one or more rooms.

    Methods:
        __str__(): Returns a string representation of the booking.
        calculate_total_price(check_in, check_out, room_category): 
        Calculates the total price based on check-in, check-out dates,
        and room category.

        get_available_rooms(room_category, check_in, check_out): 
        Retrieves rooms available for booking within a given category
        and timeframe.
    """
    booking_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rooms = models.ManyToManyField(Room)
    check_in = models.DateField(blank=False, null=False)
    check_out = models.DateField(blank=False, null=False)
    no_of_guests = models.PositiveIntegerField(blank=False, null=False)
    total_price = MoneyField(
        max_digits=10, decimal_places=2, default_currency='EUR',
        blank=False, null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Booking from {self.check_in} to {self.check_out} \
            - Total: {self.total_price}"

    class Meta:
        ordering = ['-check_in']

    @staticmethod
    def calculate_total_price(check_in, check_out, room_category):
        """
        Calculates the total price of a booking based on the check-in,
        check-out dates, and room category price.

        Returns:
            float: Total price of the booking.
        """
        if check_out <= check_in:
            raise ValueError("Check-out date must be after check-in date")
        total_nights = (check_out - check_in).days
        price_per_night = room_category.price.amount
        return price_per_night * total_nights

    @staticmethod
    def get_available_rooms(room_category, check_in, check_out):
        available_rooms = []
        rooms_in_category = Room.objects.filter(
            category=room_category, avaliable=True
        )

        for room in rooms_in_category:
            overlapping_bookings = Booking.objects.filter(
                rooms=room,
                check_in__lt=check_out,
                check_out__gt=check_in
            ).exists()

            if not overlapping_bookings:
                available_rooms.append(room)

        return available_rooms

        def save(self, *args, **kwargs):

            if self.check_out <= self.check_in:
                raise ValueError("Check-out date must be after check-in date")

            # All rooms in the same category have the same price
            room_category = self.rooms.first().category

            # Calculate total price using the static method
            self.total_price = self.calculate_total_price(
                self.check_in, self.check_out, room_category
            )

            super().save(*args, **kwargs)

    @receiver(post_save, sender='booking.Booking')
    def update_room_availability_on_save(sender, instance, created, **kwargs):
        """Mark rooms as unavailable upon booking creation."""
        if created:
            for room in instance.rooms.all():
                room.avaliable = False
                room.save()

booking/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import Booking
from rooms.models import RoomCategory, Room


class BookingForm(forms.ModelForm):
    """
    Form for booking a room.

    Fields:
        check_in (DateField): Date picker for selecting check-in date.
        check_out (DateField): Date picker for selecting check-out date.

        room_category (ModelChoiceField):
        Dropdown list of available room categories.

        no_of_guests (IntegerField):
        Input field for specifying number of guests.

    Meta:
        model (Booking): The model class to be used for this form.
        fields (list): List of fields to include in the form.
        labels (dict): Custom labels for form fields.

    Methods:
        clean(): Custom form validation method to validate dates,
        number of guests, and calculate total price based on selected
        dates and room category.
    """
    check_in = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'date', 'class': 'form-control'}),
        required=True
    )
    check_out = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'date', 'class': 'form-control'}),
        required=True
    )
    room_category = forms.ModelChoiceField(
        queryset=RoomCategory.objects.all(), required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    no_of_guests = forms.IntegerField(
        min_value=1, required=True,
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Booking
        fields = [
            'check_in', 'check_out',
            'room_category', 'no_of_guests']
        labels = {
            'check_in': 'Check in',
            'check_out': 'Check out',
            'room_category': 'Room',
            'no_of_guests': 'Number of Guests',
        }

    def clean(self):
        """Custom booking form validation."""
        cleaned_data = super().clean()
        check_in = cleaned_data.get('check_in')
        check_out = cleaned_data.get('check_out')
        no_of_guests = cleaned_data.get('no_of_guests')
        room_category = cleaned_data.get('room_category')

        # Validate check in and check out dates
        if check_in and check_out:
            if check_in < timezone.now().date():
                raise ValidationError('Check in date cannot be in the past')
            if check_out < check_in:
                raise ValidationError(
                    'Check out date cannot be before check in date')

        # Validate number of guests
        if no_of_guests < 1:
            raise ValidationError('Number of guests must be greater than 0')

        if no_of_guests > cleaned_data['room_category'].capacity:
            raise ValidationError('Number of guests exceeds maximum allowed')

        # Calculate total price if check-in, check-out,
        # and room category are valid
        # price is stored in the RoomCategory model
        if check_in and check_out and room_category:
            total_nights = (check_out - check_in).days
            price_per_night = room_category.price.amount
            total_price = price_per_night * total_nights
            cleaned_data['total_price'] = total_price

        return cleaned_data

booking/views.py
from django.views.generic import(
    TemplateView,
    DetailView,
    CreateView,
    ListView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.contrib.auth.models import User
from django.contrib import messages

from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.utils import timezone
from datetime import timedelta, datetime

from .models import Booking
from rooms.models import Room, RoomCategory
from .forms import BookingForm


# Create your views here.
class AddBooking(LoginRequiredMixin, CreateView):
    """ View for adding a booking """
    template_name = 'booking/add_booking.html'
    model = Booking
    form_class = BookingForm
    success_url = reverse_lazy('booking:booking_success')

    def form_valid(self, form):
        """ Handle valid form submissions """
    # Process the form data
        form.instance.user = self.request.user
        check_in = form.cleaned_data['check_in']
        check_out = form.cleaned_data['check_out']
        no_of_guests = form.cleaned_data['no_of_guests']
        room_category = form.cleaned_data['room_category']

        if check_out <= check_in:
            messages.error(
            self.request, 'Check-out date must be after the check-in date. \
                Please select valid dates.'
        )
            return self.form_invalid(form)
        
        # total_price calculation and room selection logic 
        # is defined in booking model
        total_price = Booking.calculate_total_price(
            check_in, check_out, room_category
        )
        available_rooms = Booking.get_available_rooms(
            room_category, check_in, check_out
        )
        
        if not available_rooms:
            messages.error(
                self.request, 'This room is not available for the \
                    selected dates.'
        )
            return self.form_invalid(form)

        else: 
            first_available_room = available_rooms[0] 
            booking = Booking.objects.create( 
                user=self.request.user,
                check_in=check_in, check_out=check_out,
                no_of_guests=no_of_guests,
                total_price=total_price,
            )
            booking.rooms.add(first_available_room)
            # Save the Booking instance to generate a booking_id
            booking.save()
            booking_id = booking.booking_id
            success_url = reverse(
                'booking:booking_success', kwargs={'pk': booking_id}
            )
            return HttpResponseRedirect(success_url)
            
            messages.success(
                self.request, 'Your reservation has been confirmed. \
                    Thank you for booking with us!'
            )
            return super().form_valid(form)

    def form_invalid(self, form):
        """Handle invalid form submissions"""
        messages.error(
            self.request, 'Your booking could not be processed. \
                Please try again or contact us for support.'
        )
        return super().form_invalid(form)


class BookingSuccess(LoginRequiredMixin, DetailView):
    model = Booking
    template_name = 'booking/booking_success.html'
    context_object_name = 'booking'


class BookingList(LoginRequiredMixin, ListView):
    """ View for listing all bookings made by the user. """
    template_name = 'booking/booking_list.html'
    context_object_name = 'bookings'
    model = Booking

    def get_queryset(self):
        """ Return bookings made by the currently logged-in user. """
        return Booking.objects.filter(user=self.request.user)


class EditBooking(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """ View for editing a booking """
    model = Booking
    form_class = BookingForm
    template_name = 'booking/edit_booking.html'
    success_url = reverse_lazy('booking:booking_list')

    def form_valid(self, form):
        """ Process the form data """
        room_category = form.cleaned_data['room_category']
        check_in = form.cleaned_data['check_in']
        check_out = form.cleaned_data['check_out']

        # check_in is a datetime.date object from form.cleaned_data
        check_in_datetime = timezone.make_aware(
            datetime.combine(check_in, datetime.min.time())
        )
        # Calculate the deadline for editing (15:00 on the day before check-in)
        check_in_deadline = check_in_datetime.replace(
            hour=15, minute=0, second=0) - timedelta(days=1)

        # Check if the current time is beyond the edit deadline
        if timezone.now() > check_in_deadline:
            messages.error(
                self.request,
                'Bookings can only be edited up to 24 hours before check-in. \
                    Please contact us for assistance.'
            )
            return self.form_invalid(form)
        
        # Proceed with room booking logic if within the allowed edit time
        available_rooms = Booking.get_available_rooms(
            room_category, check_in, check_out
        )
        if not available_rooms:
            messages.error(
                self.request, 'This room is not available for the selected \
                    dates. Please select another room or date.')
            return self.form_invalid(form)
        
        # Update booking details and room assignment
        booking = form.save(commit=False)
        old_room = booking.rooms.first() if booking.rooms.exists() else None 

        #adding the first available room
        first_available_room = available_rooms[0] if available_rooms else None
        booking.rooms.clear()  # Clear current rooms
        booking.rooms.add(first_available_room)  # Add new available room

        # Recalculate total price based on updated booking details
        total_nights = (check_out - check_in).days
        price_per_night = room_category.price.amount 
        total_price = price_per_night * total_nights
        booking.total_price = total_price
        booking.save() 

        # Make the old room available for others
        if old_room:
            old_room.avaliable = True
            old_room.save()

        messages.success(self.request, 'Your booking has been updated.')
        return super().form_valid(form)

    def test_func(self):
        """ Check if the user is the owner of the booking """
        return self.request.user == self.get_object().user

    def form_invalid(self, form):
        """ Handle invalid form submissions """
        messages.error(
            self.request, 'Your booking could not be updated. \
                Please try again or contact us for support.'
        )
        return super().form_invalid(form)


class DeleteBooking(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """ View for deleting a booking """
    model = Booking
    success_url = reverse_lazy('booking:booking_list')

    def test_func(self):
        return self.request.user == self.get_object().user

    def delete(self, request, *args, **kwargs):
        """ Perform delete operation """
        booking = self.get_object()
        success_url = 'home'

        check_in_datetime = timezone.make_aware(
            datetime.combine(check_in, datetime.min.time())
        )
        # Calculate the deadline for editing (15:00 on the day before check-in)
        check_in_deadline = check_in_datetime.replace(
            hour=15, minute=0, second=0) - timedelta(days=1)

        # Check if the current time is beyond the edit deadline
        if timezone.now() > check_in_deadline:
            messages.error(
                self.request,
                'Bookings can only be edited up to 24 hours before check-in. \
                    Please contact us for assistance.'
            )
            return HttpResponseRedirect(self.success_url)

        # Proceed with deletion if within the allowed time
        return super().delete(request, *args, **kwargs)

booking/templates/booking/add_booking.html
{% extends "base.html" %} 
{% load static %} 
{% load crispy_forms_tags %}
{% load djmoney %}
<!--Prettier ignore-->
{% block title %}Booking{% endblock %} 

{% block content %}
<div class="container">
  <form method="POST" action="{% url 'booking:add_booking' %}" class="p-2 form">
    <h1 class="text-center">Book Your Stay</h1>
    {% csrf_token %} 
    {{ form|crispy}}
    <div class="text-center">
      <button type="submit" class="btn btn-gold mx-3">Book</button>
      <a href="{% url 'rooms:roomcategory' %}" class="btn btn-red my-4">Cancel</a>
    </div>
  </form>
</div>
{% endblock %}

booking/templates/booking/booking_confirm_delete.html
{% extends "account/base.html" %} 
{% load static %}



{% block title %}
Cancel Reservation
{% endblock title %}


{% block content %}
<div class="container text-center mt-5">
    <h1>Cancel Reservation</h1>

    <p>Are you sure you want to cancel your reservation with <strong>Booking ID: {{ booking.pk }}</strong> ?</p>

    <form method="post" class="text-center">
        {% csrf_token %}
        <input type="submit" value="Cancel Booking" class="btn btn-red my-4">
        <a href="{% url 'booking:booking_list' %}" class="btn btn-gold">Keep it</a>
    </form>
</div>
<div class="container text-center mt-5">
    <h2>We are sorry to see you go!</h2>
    <p>We hope to have the pleasure of welcoming you another time.</p>
    <p><strong>If there is anything we can do to assist you in the future, 
        please don't hesitate to reach out.</strong></p>
    <p class="m-2">Thank you for considering us for your stay!</p>
</div>

{% endblock %}

booking/templates/booking/booking_list.html
{% extends "base.html" %}
<!-- Prettier Ignore-->
{% load static %}
<!-- Prettier Ignore-->
{% block title %}Reservations{% endblock %}
<!-- Prettier Ignore-->

{% block content %}
<h1 class="text-center my-5">Your Reservations</h1>
<div class="container d-flex flex-row flex-wrap justify-content-center room-categories mb-4">
    {% if bookings %}
    {% for booking in bookings %}
    <div class="card m-3 category-card" style="width: 22rem">
        <div class="card-body">
        <h2 class="card-title">{{ booking.rooms.first.category.category|lower|capfirst }}</h2>
        <hr>
        <p class="card-text">
            <strong>Booking Id:</strong> {{ booking.pk }}
            <br />
            <strong>Check-in:</strong> {{ booking.check_in }}
            <br />
            <strong>Check-in:</strong> {{ booking.check_out }}
            <br /> 
            <strong>Guests:</strong> {{ booking.no_of_guests }}
            <br />
            <strong>Total price:</strong> {{ booking.total_price }}
        </p>

        <div class="mt-auto d-flex justify-content-center">
            <a href=" {% url 'booking:edit_booking' booking.pk %}" class="btn btn-gold mx-2">Edit Booking</a>
            <a href="{% url 'booking:delete_booking' booking.pk %}" class="btn btn-red mx-2">Cancel Booking</a>
        </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="container">
        <p class="text-center">You don't have any reservations.</p>
        <p class="text-center">Check out our rooms and book your stay <a href="{% url 'rooms:roomcategory' %}">here</a>.</p>
    </div>
    {% endif %}
</div>

{% endblock %}

booking/templates/booking/booking_success.html
{% extends "base.html" %}
{% block title %}Booking Succesful{% endblock %}

{% block content %}
{% if booking %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="text-center my-5">Booking Successful</h1>
			<p class="text-center">Thank you for booking with us {{ booking.user.first_name }}!</p>
			<p class="text-center">Your booking reference is <strong>{{ booking.pk }}</strong>.</p>
			<p class="text-center mt-4">You booked a <strong>{{ booking.rooms.first.category.category|lower|capfirst }}</strong> room from {{ booking.check_in }} to {{ booking.check_out }} for {{ booking.no_of_guests }} guests.
			<p class="text-center">Total price: {{ booking.total_price }}</p>

			<h2 class="text-center mt-4">We look forward to welcoming you to our hotel!</h2>
			<p class="text-center"><strong>Check-in time is at 15:00 (3PM)</strong></p>
			<p class="text-center">If you have any questions or need any support please contact us!</p>
			<p class="text-center">We hope you'll enjoy your stay!</p>
			<p class="text-center mt-4">You can view you booking <a href="{% url 'booking:booking_list' %}">here.</a></p>
		</div>
		<div class="text-center mt-4">
			<a href="{% url 'home' %}" class="btn btn-gold">Return to Homepage</a>
			<a href="{% url 'booking:add_booking' %}" class="btn btn-book my-4">Make Another Booking</a>
		</div>
	</div>
</div>
{% else %}
<div class="container text-center">
	<h2 class="my-5">Booking details not found!</h2>
	<p>Please contact our support for assistance.</p>
	<a href="{% url 'home' %}" class="btn btn-gold mt-4">Return to Homepage</a>
</div>
{% endif %}
{% endblock %}

booking/templates/booking/edit_booking.html
{% extends "base.html" %}

{% block title %}Edit Booking{% endblock %} 

{% block content %}
<div class="container">
    <form method="POST" class="p-2 form">
        <h1 class="text-center">Edit Reservation</h1>
        {% csrf_token %}
        {{ form|crispy }}
        <div class="text-center">
            <button type="submit" class="btn btn-gold mt-2">Edit Booking</button>
        </div>
    </form>
</div>
{% endblock %}