booking/urls.py
from django.urls import path
from .views import(
    AddBooking, 
    BookingList, 
    EditBooking, 
    DeleteBooking,
    BookingSuccess
)

app_name = 'booking'

urlpatterns = [
    path('', AddBooking.as_view(), name='add_booking'),
    path('success/<int:pk>', BookingSuccess.as_view(), name='booking_success'),
    path('list/', BookingList.as_view(), name='booking_list'),
    path('edit/<int:pk>', EditBooking.as_view(), name='edit_booking'),
    path('delete/<int:pk>/', DeleteBooking.as_view(), name='delete_booking'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('about/', views.about_page, name='about'),
]

la_hotel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('profiles/', include('guests.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
    path('rooms/', include('rooms.urls'), name='rooms'),
    path('booking/', include('booking.urls'), name='booking'),
]

rooms/urls.py
from django.urls import path
from .views import RoomCategoryList, RoomCategoryDetail

app_name = 'rooms'

urlpatterns = [
    path('', RoomCategoryList.as_view(), name='roomcategory'),
    path('<int:pk>/', RoomCategoryDetail.as_view(),
         name='roomcategory_detail'),
]

rooms/models.py
from django.db import models
from djmoney.models.fields import MoneyField
from django_resized import ResizedImageField


# Create your models here.
class RoomCategory(models.Model):
    """
    Model representing a category of rooms in the hotel.

    Attributes:
        category (str): The category of the room (Standard, Deluxe, Suite).
        beds (str): The size of the beds in the room (Double, Queen, King).
        capacity (int): The maximum number of guests the room can accommodate.
        price (MoneyField): The price of the room.
        description (str): A description of the room.
        image (ResizedImageField): An image of the room,
        resized to 400x400 and saved in WEBP format.
        image_alt (str): An alternative text for the room image,
        used for accessibility and SEO.
    """
    ROOM_CATEGORIES = (
        ('STANDARD', 'Standard'),
        ('DELUXE', 'Deluxe'),
        ('SUITE', 'Suite')
        )

    BED_SIZE = (
        ('DOUBLE', 'Double'),
        ('QUEEN', 'Queen'),
        ('KING', 'King')
        )

    category = models.CharField(
        max_length=10, choices=ROOM_CATEGORIES, blank=False, null=False)
    beds = models.CharField(
        max_length=10, choices=BED_SIZE, blank=False, null=False)
    capacity = models.PositiveIntegerField(blank=False, null=False)
    price = MoneyField(
        max_digits=10, decimal_places=2, default_currency='EUR',
        blank=False, null=False)
    description = models.TextField(
        max_length=10000, help_text="Enter a description of the room",
        blank=True, null=True)
    image = ResizedImageField(
        size=[400, 400],
        crop=['middle', 'center'],
        quality=75,
        upload_to="room-categories/",
        force_format="WEBP",
        blank=False,
        null=False,
        max_length=1000
    )
    image_alt = models.CharField(
        max_length=100, help_text="Enter a breif description of the image",
        default="Default room image",
        blank=False, null=False
    )

    def __str__(self):
        return f"{self.category} || Bed: {self.beds} - Guests: {self.capacity}\
        || Price: {self.price}"


class Room(models.Model):
    """
    Model representing a room in the hotel.

    Attributes:
        room_number (str): The unique identifier for the room.
        category (ForeignKey): The category the room belongs to.
        available (bool): Whether the room is available for booking.
    """
    room_number = models.CharField(
        max_length=10, unique=True, blank=False, null=False)
    category = models.ForeignKey(RoomCategory, on_delete=models.CASCADE)
    avaliable = models.BooleanField(
        default=True, help_text="Check if the room is avaliable")

    class Meta:
        unique_together = (('room_number', 'category'),)

    def __str__(self):
        return f"{self.room_number} - {self.category} - {self.avaliable}"

rooms/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import RoomCategory, Room


class RoomCategoryList(ListView):
    """ 
    List view for displaying room categories.

    This view retrieves a list of RoomCategory objects and renders them
    in the specified template. The room categories are ordered by price.
    """
    model = RoomCategory
    template_name = 'rooms/roomcategory_list.html'
    context_object_name = 'categories'
    ordering = ['price']


class RoomCategoryDetail(DetailView):
    """
    Detail view for displaying a single room category.

    This view retrieves a RoomCategory object based on the primary key (pk)
    and renders it in the specified template.
    """
    model = RoomCategory
    template_name = 'rooms/roomcategory_detail.html'
    context_object_name = 'category'

rooms/templates/rooms/roomcategory_detail.html
{% extends "base.html" %}

{% block title %}Room Detail - {{ category.category }}{% endblock %}

{% block content %}
<div class="container my-5">
    <a href="{% url 'rooms:roomcategory' %}" class="mb-4"><i class="fa-solid fa-arrow-left icon back-icon" aria-hidden="true"></i>
    <span class="sr-only">Go back to room categories</span></a>
    <div class="row text-center">
        <div class="col-lg-6 col-md-12 mb-4 mb-lg-0">
            <img src="{{ category.image.url }}" alt="{{ category.image_alt }}" class="img-fluid">
        </div>
        <div class="col-lg-6 col-md-12 mt-4">
            <h1 class="text-center">{{ category.category|lower|capfirst }}</h1>
            <p class="text-center">{{ category.beds|lower|capfirst }} Bed, {{ category.capacity }} Guests</p>
            <p class="text-center">{{ category.price }}</p>
            <hr>
            <p class="text-center my-4">{{ category.description|safe }}</p>
            <div class="text-center">
                <a href="{% url 'booking:add_booking' %}" class="btn btn-book">Book Now</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

rooms/templates/rooms/roomcategory_list.html
{% extends "base.html" %}
<!-- Prettier Ignore-->
{% load static %}
<!-- Prettier Ignore-->
{% block title %}Rooms{% endblock %}
<!-- Prettier Ignore-->
{% block content %}

<h1 class="text-center p-2 d-block my-4">Rooms</h1>

<div class="container d-flex flex-row flex-wrap justify-content-center room-categories mb-4">
	{% for category in categories %}
	<div class="card m-3 category-card" style="width: 18rem">
	<!-- Check if the category image exists -->
	{% if category.image %}
		<img
			src="{{ category.image.url }}"
			class="card-img-top"
			alt="{{ category.image_alt }}"
		/>
	{% else %}
		<!-- Display the default image if no image was uploaded -->
		<img
			src="{% static 'images/default-room.webp' %}"
			class="card-img-top"
			alt="Default Room Image"
		/>
	{% endif %}
		<div class="card-body">
			<h2 class="card-title">{{ category.category|lower|capfirst }}</h2>
			<p class="card-text">
			{{ category.beds|lower|capfirst }} Bed, {{ category.capacity }} Guests
			<br>
			{{ category.price }}
			<br>
			{{ category.description|truncatewords:20|safe }}
			</p>
			<div class="mt-auto d-flex justify-content-center">
				<a href="{% url 'rooms:roomcategory_detail' category.id %}" class="btn btn-gold">View Room</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}